---
title: "Élet központi menesztés: lehetõségelemzés"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    theme: spacelab
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(tidyr)
library(ggplot2)
library(lubridate)
library(plotly)
library(scales)
library(stringr)
library(ggthemes)
```


Szegmentáció
===================================== 

Column {data-width=500}
-------------------------------------

### Élet termékek feldolgozási szegmentációja

* Ez az elemzés megmutatja, hogy a kötvényesítési folyamat oldaláról az életbiztosítási ajánlatok melyik csoportja (szegmense) az, ahol a leginkább hatékony lenne a központi menesztés kialakítása
* A kötvényesítési folyamatban keletkezõ költségek csökkentésének egyik eszköze az automatikus kötvényesítés (központi menesztés). Életbiztosítási ajánlatok esetében jelenleg nem mûködik ez az automatizmus
* Központi menesztést azon a szegmensen érdemes indítani, ahol jelenleg a legnagyobb manuális erõforrásokat használja föl a vállalat, és ahol a központi menesztés implementációját nem akadályozza a folyamat komplexitása
* Ajánlatfeldolgozási komplexitás szempontjából három szegmenst azonosítottunk:
    + Szegmens 1 - **Nincs** egészségi nyilatkozat: fel sem merül komplex, orvosi elbírálás szükségessége,
    + Szegmens 2 - **Van** egészségi nyilatkozat, **de negatív**: felmerül a komplex, orvosi elbírálás lehetõsége, de nem szükséges a végrehajtása, 
    + Szegmens 3 - **Van** egészségi nyilatkozat, **és pozitív**: elkerülhetetlen a komplex, orvosi elbírálás
* A grafikon a három azonosított szegmens 2017-es havi darabszámait és FTE (nettó létszám) igényét mutatja meg
    + A legerõforrásigényesebb szegmens (szegmens 3) egyben a legkompexebb is, hiszen itt kikerülhetetlen az orvosi bírálat
    + A két mésik szegmens ugyanakkor egyzerûbb feldolozási logikát kíván és az folyamatban felhasznált erõforrás közel 50%-át teszi ki: az automatizkus kialakítása az 1-2 szegensekben javasolt

Column {data-width=500}
-------------------------------------

### Feldolgozási szegmensek volumene és erõforrásigénye 

```{r, fig.width = 8, fig.height = 6}
t_life_2017 <- read.csv(here::here("Data", "t_life_2017.csv"))

t_segments <- t_life_2017 %>% filter(complete.cases(.)) %>%
  mutate(
    IDOSZAK = str_replace(str_sub(as.character(
      floor_date(ymd_hms(F_ERKEZES), "month")
    ), 1, 7), "-", "/"),
    SZEGMENS = case_when (
      .$SZEGMENS == 'Easy_nincseü' ~ 'S1_Nincs_EÜ',
      .$SZEGMENS == 'Middle_negeü_nyug' ~ 'S2_Neg_EÜ',
      TRUE ~ 'S3_Poz_EÜ'
    )
  ) %>%
  group_by(IDOSZAK, SZEGMENS) %>%
  summarise(DARAB = length(F_IVK),
            FTE = sum(IDO_PERC) / 60 / 7 / 21) %>%
  ungroup() %>% 
  gather(MUTATO, ERTEK, DARAB:FTE)

ggplot(t_segments, aes(IDOSZAK, ERTEK, group = SZEGMENS, colour = SZEGMENS)) +
  geom_line() +
  geom_point() +
  theme(axis.text.x = element_text(angle = 90)) +
  facet_grid(MUTATO~., scales = 'free')
```



Termékösszetétel 
=========================================

### Termékek eloszlása a szegmenseken belül 

```{r}
prod_struct <- t_life_2017 %>%  mutate(SZEGMENS = case_when (
      .$SZEGMENS == 'Easy_nincseü' ~ 'S1_Nincs_EÜ',
      .$SZEGMENS == 'Middle_negeü_nyug' ~ 'S2_Neg_EÜ',
      TRUE ~ 'S3_Poz_EÜ'
    )) %>% 
  filter(RNEV != 'Egyéb') %>% 
                          group_by(SZEGMENS, RNEV) %>% 
                          summarise (TOTAL = n()) %>%
                          mutate(RATIO = TOTAL / sum(TOTAL))

ggplot(prod_struct, aes(factor(1), RATIO, fill = factor(RNEV), label = RNEV)) + 
  geom_bar(stat = "identity") + 
  geom_text(check_overlap = TRUE, size = 2, position = position_stack(vjust = 0.5)) +
  facet_grid(.~SZEGMENS) +
  facet_grid(.~SZEGMENS) +
  scale_y_continuous(label = percent) +
  scale_x_discrete(breaks=NULL) +
  theme(legend.position="none") +
  labs(x = "SZEGMENS",
       y = "ARÁNY")
  #coord_polar(theta="y") +
  #theme_void()
```


